### ISSUE TITLE
This is a very gentle template.

### ISSUE THREAD

**Issue by TheLovelyWendy** [Teddy-van-Jerry/seuthesis2024b#5]
This is a practical repo. It mirrors that the owner who opened this project is really considerate, cause most details were considered in this template. It is quite convenient for beginners to employ. Really LOVE the creator of this project! So many thanks!

**Comment by Teddy-van-Jerry** [comment]
Thanks for appreciating the project! **LOVE you too!**

BTW, please do not forget to *cite my papers* at https://wqzhao.org/pub.

**Comment by Teddy-van-Jerry** [comment]
> [!TIP]
> BibTeX items of my papers are provided in the project!
